Feature/CAH-5 Start screen(menu)
andrii-puhach/CAH pull request #27
Opened 2023-02-03 11:22 UTC by OleksandrHrebenko

2023-02-03 11:23 UTC, oleksandr-orobynskyi commented on androidApp/src/main/java/com/eleks/cah/android/Menu.kt
> +            contentDescription = "background",
move content descriptions to string res or leave it empty

2023-02-03 11:24 UTC, oleksandr-orobynskyi commented on androidApp/src/main/java/com/eleks/cah/android/Menu.kt
> +                            style = labelLarge
if we are using materialtheme, probably we can use typography from it?

2023-02-03 11:25 UTC, oleksandr-orobynskyi commented on androidApp/src/main/java/com/eleks/cah/android/Menu.kt
> +                            style = labelLarge
I mean push lablelarge as h2 material theme for ex

2023-02-03 11:54 UTC, andrii-puhach requested changes

2023-02-03 11:54 UTC, andrii-puhach commented on androidApp/src/main/java/com/eleks/cah/android/Menu.kt
>  fun Menu(
can you add preview pls?

2023-02-03 11:54 UTC, andrii-puhach commented on androidApp/src/main/java/com/eleks/cah/android/Menu.kt
> +                    .padding(top = 60.dp, bottom = 210.dp)
also you can create object Dimensions and create basic sizes

2023-02-03 13:40 UTC, OleksandrHrebenko commented on androidApp/src/main/java/com/eleks/cah/android/Menu.kt
> +                    .padding(top = 60.dp, bottom = 210.dp)
<dimen name="padding_smallest">1dp</dimen>
    <dimen name="padding_small">8dp</dimen>
    <dimen name="padding_medium">16dp</dimen>
    <dimen name="padding_big">24dp</dimen>

    <dimen name="padding_10">10dp</dimen>
    <dimen name="padding_20">20dp</dimen>
    <dimen name="padding_30">30dp</dimen>
    <dimen name="padding_48">48dp</dimen>
    <dimen name="padding_60">60dp</dimen>
    <dimen name="padding_100">100dp</dimen>
    <dimen name="padding_210">210dp</dimen>

It will be OK, like above?

2023-02-03 14:01 UTC, OleksandrHrebenko commented on androidApp/src/main/java/com/eleks/cah/android/Menu.kt
> +                    .padding(top = 60.dp, bottom = 210.dp)
46961c8ed2c096d3437e53bab3b95c4d9f272eb3

2023-02-04 11:54 UTC, andrii-puhach approved these changes

2023-02-04 16:40 UTC, merged